title: Shirin Dance
description: Scuola di danza orientale, folklore, fusion, FCBD®, Bollywood
url: "https://shirindance.github.io"

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

consent:

  version: "1.0"

  privacy_template:
    url: "https://raw.githubusercontent.com/glispisotti/glispisotti/main/consent/privacy.html"

  privacy:
    titolare: "Laura Porceddu"
    sede: ""
    email: "glispisotti@gmail.com"
    pec: ""

  hosting:
    provider: "GitHub Pages"
    privacy_url: "https://docs.github.com/it/site-policy/privacy-policies/github-general-privacy-statement"

  services:
    analytics: true
    youtube: true
    maps: true

collections:
  newsletters:
    output: true
    permalink: /newsletter/:slug/

  seminari:
    output: true
    permalink: /seminari/:slug/

  news:
    output: true
    permalink: /news/:slug/

  eventi:
    output: true
    permalink: /eventi/:slug/

  ultima_ora:
    output: true
    permalink: /ultima_ora/:slug/

  archivio_notizie:
    output: true
    permalink: /archivio_notizie/:slug/