title: Shirin Dance
description: Scuola di danza orientale, folklore, fusion, FCBD®, Bollywood
url: "https://shirindance.github.io"

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  newsletters:
    output: true
    permalink: /newsletter/:slug/

  seminari:
    output: true
    permalink: /seminari/:slug/